service:
  name: encore-local

spring:
  redis:
    host: localhost
    port: 6379

profile:
  location: url:https://raw.githubusercontent.com/svt/encore/master/src/test/resources/profile/profiles.yml

encore-settings:
  concurrency: 3
  local-temporary-encode: false
  poll-initial-delay: 1s
  poll-delaly: 1s

  audio-mix-presets:
    default:
      pan-mapping:
        6:
          2: stereo|c0=1.0*c0+0.707*c2+0.707*c4|c1=1.0*c1+0.707*c2+0.707*c5
    de:
      fallback-to-auto: true
